### ISSUE TITLE
[Emokymai]: Velykų atostogos → Vėlinių atostogos

### ISSUE THREAD

**Issue by MartaPurvinyte** [mokymai/taisymai-2021#10]
1. **Dalykas:** BS-2021
2. **Netikslumo vieta:** „Emokymai“ svetainė
3. **Nuoroda į resursą (URL):** https://emokymai.vu.lt/course/view.php?id=2306
4. **Glaustai aprašykite netikslumą:** ... 
6. **Netikslumo tekstas:** 
Velykų atostogos!
7. **Siūlomas taisymo tekstas:** Vėlinių ilgasis savaitgalis!
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
... 
![klaida](https://user-images.githubusercontent.com/89739669/132101908-bfc315de-9c1c-4816-9904-e143ceb07fe2.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Šitos sekcijos apskritai neturėjote matyti.
