### ISSUE TITLE
Teorijos svetainė (tyrimų eiga 2.2  netikslumas) mokliškai→ moksliškai

### ISSUE THREAD

**Issue by donatasbar** [mokymai/taisymai-2021#112]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):*https://mokymai.github.io/biostatistika/tyrimu-eiga.html* 
4. **Glaustai aprašykite netikslumą:*Rašybos klaida*  

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:* Kodėl teiginio neįmanoma „mokliškai įrodyti“ (angl. proof), bet galima falsifikuoti?* ... 
6. **Netikslumo tekstas: *mokliškai* .
7. **Siūlomas taisymo tekstas:  *moksliškai* 
8. **Ekrano nuotrauka („Screenshots“)*
![image](https://user-images.githubusercontent.com/78752013/107386679-bff8f980-6afc-11eb-9777-944d4799d034.png)
* su pažymėta netikslumo vieta.
...

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Langelius reikia užpildyti `[x]`, o ne `[ x ]` (be tarpų).
