### ISSUE TITLE
[Biostatistika]: Stjudento → studento (rašyba)

### ISSUE THREAD

**Issue by Juditat** [mokymai/taisymai-2021#113]
1. **Dalykas:** BS-2021 
2. **Netikslumo vieta:** Biostatistikos teorijos svetainė (`mokymai.github.io/biostatistika`)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/skaitines-suvestines.html 
4. **Glaustai aprašykite netikslumą:** 
rašybos klaida 
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** t statistika Stjudento t teste 
6. **Netikslumo tekstas:** Stjudento
7. **Siūlomas taisymo tekstas:** studento
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/89836787/134394402-cf206bd2-30ce-4a34-b289-a7e72a4e2887.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Tai mokslininko slapyvardis: https://en.wikipedia.org/wiki/William_Sealy_Gosset
