### ISSUE TITLE
Pratybų svetainė: nuotoliniu būdų → nuotoliniu būdu 

### ISSUE THREAD

**Issue by AgneMike** [mokymai/taisymai-2021#124]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/programa-r/apie.html
4. **Glaustai aprašykite netikslumą:**  

6. **Netikslumo tekstas:** vyks nuotoliniu būdų
7. **Siūlomas taisymo tekstas:** vyks nuotoliniu būdu
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="613" alt="klaida" src="https://user-images.githubusercontent.com/78725206/107420042-23951e00-6b21-11eb-9253-f761d01b1d27.PNG">

Patvirtinkite pažymėdami [x]:

- [ x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [ x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Šita dalis užpildyta netinkamai:
![image](https://user-images.githubusercontent.com/12725868/107434764-dd958580-6b33-11eb-8b63-2ace078519f5.png)

Turi būti `[x]`, ne `[ x]` (be tarpų).

**Comment by GegznaV** [comment]
Kaip redaguoti savo žinutę: 
![image](https://user-images.githubusercontent.com/12725868/107659875-514ca500-6c90-11eb-87fb-ae3ec9f30732.png)
