### ISSUE TITLE
Pratybų svetainė: joint → join (abu žodžiai reiškia skirtingus dalykus )

### ISSUE THREAD

**Issue by ArnoldasM-lab** [mokymai/taisymai-2021#135]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/programa-r/paskyros.html
4. **Glaustai aprašykite netikslumą: Fakto klaida .Join(prisijungti,sujungti) ir joint(sąnarys) yra skirtingi žodžiai. 

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ... 
6. **Netikslumo tekstas:** Spauskite mygtuką „Joint Group“
7. **Siūlomas taisymo tekstas:**  Spauskite mygtuką „Join Group“
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78723524/107615063-2f353180-6c54-11eb-9026-147dc1ca17ac.png)

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x ] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Pataisykite iš `[x ]` į `[x]`:
![image](https://user-images.githubusercontent.com/12725868/107659088-742a8980-6c8f-11eb-9b84-cf33b72e6f05.png)

![image](https://user-images.githubusercontent.com/12725868/107659261-a340fb00-6c8f-11eb-81c2-70cab25ebb2f.png)


Tada parašykite dar vieną žinutę į šį pokalbį. Įskaitysiu taškus.
