### ISSUE TITLE
Pratybų svetainė: naudijamas → naudojamas (rašybos klaida )

### ISSUE THREAD

**Issue by ArnoldasM-lab** [mokymai/taisymai-2021#137]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/bs-2021-pratybos/diegimas.html
4. **Glaustai aprašykite netikslumą:**  

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ... 
6. **Netikslumo tekstas:** Rašybos klaida ,vietoje i reikia rašyti o
7. **Siūlomas taisymo tekstas:** naudojamas kodas
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78723524/107629414-c0170780-6c6a-11eb-8d36-c5a2d2f68044.png)

Patvirtinkite pažymėdami [x]:

- [ x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x ] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Ta pati pastaba: 
![image](https://user-images.githubusercontent.com/12725868/107659618-fca92a00-6c8f-11eb-93ee-5ae6f34102b9.png)
