### ISSUE TITLE
[R-2021 pratybos]: Trūksamoms  → Trūkstamoms (praleista raidė)

### ISSUE THREAD

**Issue by cathwood** [mokymai/taisymai-2021#146]
1. **Dalykas:** R-2021
2. **Netikslumo vieta:** R-2021 pratybų svetainė
3. **Nuoroda į resursą (URL):** https://mokymai.github.io/r-2021-pr/s08.html
4. **Glaustai aprašykite netikslumą:** praleista raidė 
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**  Trūksamoms reikšmėms spalvą 
6. **Netikslumo tekstas:**  Trūksamoms reikšmėms spalvą
7. **Siūlomas taisymo tekstas:**  Trūkstamoms reikšmėms spalvą
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/89642643/139602146-cdc85499-c119-4010-a324-f4216af56ef9.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dėkui
