### ISSUE TITLE
[R-2021 pratybos]: sunkcija → funkcija (rašybos klaida)

### ISSUE THREAD

**Issue by cathwood** [mokymai/taisymai-2021#147]
1. **Dalykas:** R-2021
2. **Netikslumo vieta:** R-2021 pratybų svetainė
3. **Nuoroda į resursą (URL):** https://mokymai.github.io/r-2021-pr/s08.html
4. **Glaustai aprašykite netikslumą:** rašybos klaida 
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** pasiekiami naudojant sunkciją stat
6. **Netikslumo tekstas:** sunkciją stat
7. **Siūlomas taisymo tekstas:**  funkciją stat
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/89642643/139602216-401e5add-29fe-47cd-8c74-e242d4d7237a.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dėkui
