### ISSUE TITLE
[R-2021 pratybos]: tašų salva atitinta → taškų spalva atitinka (rašybos klaidos)

### ISSUE THREAD

**Issue by cathwood** [mokymai/taisymai-2021#149]
1. **Dalykas:** R-2021
2. **Netikslumo vieta:** R-2021 pratybų svetainė
3. **Nuoroda į resursą (URL):** https://mokymai.github.io/r-2021-pr/s08.html
4. **Glaustai aprašykite netikslumą:** rašybos klaidos 
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** tašų salva atitinta  
6. **Netikslumo tekstas:**tašų salva atitinta 
7. **Siūlomas taisymo tekstas:** taškų spalva atitinka 
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/89642643/139602342-2a2199bf-a284-4bea-945a-f31caca3eaed.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dėkui :)
