### ISSUE TITLE
[R-2021 pratybos]: data → tada (ne tas žodis)

### ISSUE THREAD

**Issue by cathwood** [mokymai/taisymai-2021#151]
1. **Dalykas:** R-2021
2. **Netikslumo vieta:** R-2021 pratybų svetainė
3. **Nuoroda į resursą (URL):** https://mokymai.github.io/r-2021-pr/s08.html#s08
4. **Glaustai aprašykite netikslumą:** ne tas žodis 
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** data abu grafikus
6. **Netikslumo tekstas:** data abu grafikus
7. **Siūlomas taisymo tekstas:** tada abu grafikus
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/89642643/140580094-b4e6c1f0-0c3c-4846-b5c1-513a30a878b7.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dėkui
