### ISSUE TITLE
[R-2021 pratybos]: 1% - 10 kartų mažiau → 1% - 10 kartų mažiau (praleistas 0)

### ISSUE THREAD

**Issue by cathwood** [mokymai/taisymai-2021#153]
1. **Dalykas:** R-2021
2. **Netikslumo vieta:** R-2021 pratybų svetainė
3. **Nuoroda į resursą (URL):** https://mokymai.github.io/r-2021-pr/s09.html
4. **Glaustai aprašykite netikslumą:** praleistas skaičius 
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** imties dydį sumažinkite 10 kartų
6. **Netikslumo tekstas:** imties dydį sumažinkite 10 kartų
7. **Siūlomas taisymo tekstas:** imties dydį sumažinkite 100 kartų
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/89642643/140627093-d778de8a-e95a-4cea-bb3b-5d3e0bbc9f23.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dėkui!
