### ISSUE TITLE
[vieta]: netikslumas → taisymas (netikslumo esmė)

### ISSUE THREAD

**Issue by kornelissa** [mokymai/taisymai-2021#158]
Sveitainė: atsitiktinį -> atsitiktinė
Temos pavadinime apibūdinkite netikslumo esmę, kuri kitiems skaitytojams padėtų bent iš dalies identifikuoti netikslumą neatsidarius temos:
1. Parašykite, kur yra netikslumas: kurso svetainėje, „Emokymai“ sistemoje ar skaidrėse, pvz., "Svetainė:";
2. Apibūdinkite netikslumo esmę. Jei galima, tokiu formatu: netikslumas → taisymas;
Pvz.:
„Svetainė: kopppiuteris → kompiuteris“
„Skaidrės: praleistas žodis "tačiau"“
 -->
1. **Kursas:** Biostatistika (BS-2021)
2. emokymai.lt sistemos T02 atsiskaityme viename iš klausimų esanti rašybos klaida
3. **Bylos pavadinimas ar nuoroda (URL):** ...
4. **Glaustai aprašykite netikslumą: gramatinė rašybos klaida
 
5. **Nukopijuokite visą sakinį su netikslumu:**

6. **Netikslumo tekstas:** atsistiktinį
7. **Siūlomas taisymo tekstas:** atsitiktinė
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78532137/107862165-966d0480-6e53-11eb-8b55-3a0cb31a8490.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Apie netikslumus testuose reikia pranešti dėstytojui asmeniškai, o ne per GitHub
