### ISSUE TITLE
[Emokymai]: Rekšmingumo → Reikšmingumo (rašybos klaida T10 teste)

### ISSUE THREAD

**Issue by Tautvydasboch** [mokymai/taisymai-2021#159]
1. **Dalykas:** BS-2021
2. **Netikslumo vieta:** „Emokymai“ svetainė
3. **Nuoroda į resursą (URL):** https://emokymai.vu.lt/mod/quiz/attempt.php?attempt=87549&cmid=46424&page=6
4. **Glaustai aprašykite netikslumą:** rašybos klaida 
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Rekšmingumo lygmuo 
6. **Netikslumo tekstas:** Rekšmingumo
7. **Siūlomas taisymo tekstas:** Reikšmingumo
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Apie netikslumus testuose ra6ykite man tiesiogiai, o ne per GH.
