### ISSUE TITLE
P02-1 (v1.0) sk.7: kablelis po tokie, 3 punktas → nereikia kablelio (skaidrės)

### ISSUE THREAD

**Issue by austejaru** [mokymai/taisymai-2021#161]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P02 v1.0 
4. **Skaidrės numeris:** ... 
5. **Glaustai aprašykite netikslumą:** Skyrybos klaida.

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**  Tokie, kaip kintamojo; 
7. **Netikslumo tekstas:** Tokie, kaip kintamojo.
8. **Siūlomas taisymo tekstas:** Tokie kaip kintamojo (Nereikia kablelio, nes nėra šalutinis sakinys (nėra gramatinio centro). Be to, negali būti skiriamas kaip palyginimas, nes taip pat nėra gramatinio centro).
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

![Screenshot (579)_LI](https://user-images.githubusercontent.com/78702404/107876214-4df22d00-6ecd-11eb-8bd4-1f6cc21baf0b.jpg)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
http://www.vlkk.lt/vlkk-nutarimai/nutarimai/nutarimas-del-pasirenkamosios-skyrybos-taisykliu
6 punktas:

> 6. Lyginamieji posakiai
>
> Lyginamieji posakiai, prisijungę prie būdvardiškųjų įvardžių toks (-ia), toks (-ia) pat, šitoks (-ia), koks (-ia), kitoks (-ia) ir pan., taip pat prie įvardinių prieveiksmių taip, kitaip, tiek ir pan., gali būti išskiriami, jei norima parodyti jų prasminį ir intonacinį savarankiškumą

**Comment by GegznaV** [comment]
Nebent galite pagrįsti, kad yra kitaip.

**Comment by austejaru** [comment]
Na, kadangi yra taisyklė ir apie pasirenkamąją skyrybą, nieko daugiau
pasakyti negaliu.

2021-02-15, pr, 17:12 Vilmantas Gegzna <notifications@github.com> rašė:
