### ISSUE TITLE
Pratybų svetainė: netikslumas → taisymas 4.6.3 elementų eilės numerių žymėjimas. 78 vietoje 58

### ISSUE THREAD

**Issue by mmirauskaite** [mokymai/taisymai-2021#162]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/bs-2021-pratybos/s01.html#svarbiausi-rs-langai-video
4. **Glaustai aprašykite netikslumą: 4.6.3 skyriuje, po pirmu pavyzdžiu parašyta:
"Pavyzdyje matome, kad elemento, kurio eilės numeris yra [69], reikšmė yra 78." KLAIDA 78 - turėtų būti 58

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** reikšmė yra 78. 
6. **Netikslumo tekstas:** Pavyzdyje matome, kad elemento, kurio eilės numeris yra [69], reikšmė yra 78
7. **Siūlomas taisymo tekstas:** Pavyzdyje matome, kad elemento, kurio eilės numeris yra [69], reikšmė yra 58
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...

<img width="1440" alt="Screenshot 2021-02-14 at 16 12 23" src="https://user-images.githubusercontent.com/78866991/107879123-adf1cf00-6edf-11eb-986d-2c59450e65b9.png">

Patvirtinkite pažymėdami [x]:
- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji. 
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Išbandykite:

```r
x <- 10:100
x
x[69]
```
