### ISSUE TITLE
P02-1 (v1.0) sk.47: pasikliautinąjį intervalą → pasikliautinojo intervalo (skaidrės)

### ISSUE THREAD

**Issue by austejaru** [mokymai/taisymai-2021#166]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P02-1 v1.0
4. **Skaidrės numeris:** ... 
5. **Glaustai aprašykite netikslumą:** Nesuderinti linksniai

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** SE atitinka 68% vidurkio pasikliautinąjį intervalą
7. **Netikslumo tekstas:**68% vidurkio pasikliautinąjį intervalą
8. **Siūlomas taisymo tekstas:** 68% vidurkio pasikliautinojo intervalo

9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![Screenshot (610)_LI](https://user-images.githubusercontent.com/78702404/107925315-f0b5b480-6f7c-11eb-966d-339c22e40d44.jpg)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Įprastai skaičiuojamas devyniasdešimt penkių procentų pasikliautinasis intervalas. Čia yra vartojamas statistinis terminas „šešiasdešimt aštuonių procentų pasikliautinasis intervalas“.
