### ISSUE TITLE
T02 [!] Žinių patikrinimas: aprašomoji stat. (1 kintamasis), 9 klausimas; atsitiktinį → atsitiktinė

### ISSUE THREAD

**Issue by zuklijaArnas** [mokymai/taisymai-2021#167]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** ... T02
3. **Bylos pavadinimas ar nuoroda (URL):** ...https://emokymai.vu.lt/mod/quiz/attempt.php?attempt=191351&cmid=147105&page=8
4. **Glaustai aprašykite netikslumą:**  Rašybos klaida
 
5. **Nukopijuokite visą sakinį su netikslumu:** ...Imtis buvo visiškai atsitiktinį

6. **Netikslumo tekstas:** ... atsitiktinį 
7. **Siūlomas taisymo tekstas:** ...atsitiktinė
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...

![image](https://user-images.githubusercontent.com/78698354/107925369-05924800-6f7d-11eb-8523-0794773fccce.png)

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x ] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
![image](https://user-images.githubusercontent.com/12725868/107958981-705a7800-6fab-11eb-88f0-46292cf22431.png) 
↓↓↓↓
![image](https://user-images.githubusercontent.com/12725868/107959016-7e0ffd80-6fab-11eb-827b-18a0780211b1.png)

??? `[x]` nėra tas pats, kas `[x ]`

**Comment by GegznaV** [comment]
Apie netikslumus teste reikia rašyti man asmeniškai, o ne per GitHub

**Comment by GegznaV** [comment]
Dublikatas #158, bet #158 neteisingai užpildytas pavadinimas.
