### ISSUE TITLE
Pratybų svetainė: stringtis → strigtis 

### ISSUE THREAD

**Issue by rstumbraite** [mokymai/taisymai-2021#168]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/bs-2021-pratybos/s02.html#uzduotys-s02
4. **Glaustai aprašykite netikslumą:**  rašybos klaida (nėra žodžio "stringtis" lietuvių kalbos žodyne)
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Programoje „RStudio“ buvo tam tikra stringtis (tiesą sakant, galbūt ji jau ištaisyta),...
6. **Netikslumo tekstas:** tam tikra stringtis
7. **Siūlomas taisymo tekstas:** tam tikras strigimas
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/78716050/107927359-923e0580-6f7f-11eb-88ed-d79f286d03d6.png">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
**Strigtis** (angl. bug) – tai šiame kurse vartojamas terminas.
