### ISSUE TITLE
Pratybų svetainė: pateiktą → pateikta (rašyba)

### ISSUE THREAD

**Issue by golendraite** [mokymai/taisymai-2021#177]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/bs-2021-pratybos/diegimas.html#diegti-r-paketus
4. **Glaustai aprašykite netikslumą:**  rašybos klaida

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** bus pateiktą keletas sprendimų 
6. **Netikslumo tekstas:** pateiktą
7. **Siūlomas taisymo tekstas:** pateikta
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78824109/108188147-e8de4780-7117-11eb-9776-bfb732ad6fbd.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
#176 problemos dublikatas

**Comment by golendraite** [comment]
Klaida ta pati, bet kitoje vietoje. Taigi čia ne dublikatas

**Comment by GegznaV** [comment]
Pataisiau
