### ISSUE TITLE
bet -> bent (praleista raidė)

### ISSUE THREAD

**Issue by kornelissa** [mokymai/taisymai-2021#178]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/bs-2021-pratybos/s02.html#uzduotys-s02
4. **Glaustai aprašykite netikslumą: rašybos klaida

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Žinoti bet vieną taikymo pavyzdį). 
6. **Netikslumo tekstas:** bet
7. **Siūlomas taisymo tekstas:** bent
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78532137/108202129-534bb380-7129-11eb-983c-60225a4accd8.png)

Patvirtinkite pažymėdami [x]:

- [ x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Kai dedate x'us juos reikia dėti ne šitaip:
![image](https://user-images.githubusercontent.com/12725868/108212255-54371200-7136-11eb-87f5-946f434d7f38.png)

O šitaip (be tarpų):
![image](https://user-images.githubusercontent.com/12725868/108212332-687b0f00-7136-11eb-956b-c2c2edc5e567.png)
