### ISSUE TITLE
Teorijos svetainė: lentele → lentelę

### ISSUE THREAD

**Issue by MoniRol** [mokymai/taisymai-2021#183]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija), 4.4 Suvestinės vienam kintamajam
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/skaitines-suvestines.html
4. **Glaustai aprašykite netikslumą:** Nesuderinti linksniai (galininkas - įnagininkas) 

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Jei norime atvaizduoti dažnių lentele, skaitinės reikšmės gali būti grupuojamos 
6. **Netikslumo tekstas:** lentele
7. **Siūlomas taisymo tekstas:** lentelę
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

![1](https://user-images.githubusercontent.com/78532995/108591602-3b1aa500-7372-11eb-8482-040f73e2ca7e.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Atvaizduoti kaip, o ne ką: [...] jei (reikšmes) norime atvaizduoti lentele [...]

**Comment by GegznaV** [comment]
Pridėsiu žodį "duomenys"
