### ISSUE TITLE
[Pratybų svetainė]: sąsiuvinys -> sąsiuvinis

### ISSUE THREAD

**Issue by Juditat** [mokymai/taisymai-2021#2]
1. **Dalykas:** BS-2021
2. **Netikslumo vieta:** Biostatistikos pratybų svetainė
3. **Nuoroda (URL):** https://mokymai.github.io/programa-r/apie.html
4. **Glaustai aprašykite netikslumą:** rašybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** "Sąsiuvinys, užrašai, rašiklis ir"
6. **Netikslumo tekstas:** sąsiuvinys
7. **Siūlomas taisymo tekstas:** sąsiuvinis
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
[sąsiuvinys į sąsiuvinis.docx](https://github.com/mokymai/taisymai-2021/files/7098378/sasiuvinys.i.sasiuvinis.docx)
 
![image](https://user-images.githubusercontent.com/89836787/131833480-dfa8b732-6527-4ed4-93b2-ef6ca479a95b.png)
    

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Pridėjau ekrano nuotrauką su pažymėta netikslumo vieta.
- [x] Formą užpildžiau tinkamai.
****

**Comment by GegznaV** [comment]
http://www.vlkk.lt/konsultacijos/4661-sasiuvinis

**Comment by GegznaV** [comment]
Dėkui.
