### ISSUE TITLE
P03-1 (v1.0) sk.22: reikšmė neužeinanti → reikšmė, neužeinanti (skaidrės, trūksta kablelio)

### ISSUE THREAD

**Issue by rstumbraite** [mokymai/taisymai-2021#202]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P03-1 v1.0
4. **Skaidrės numeris:** 22
5. **Glaustai aprašykite netikslumą:** skyrybos klaida (tai privalomoji skyryba)
6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Didžiausia reikšmė neužeinanti už vidinio barjero.
7. **Netikslumo tekstas:** reikšmė neužeinanti
8. **Siūlomas taisymo tekstas:** reikšmė, neužeinanti
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="790" alt="image" src="https://user-images.githubusercontent.com/78716050/108887439-eba6d400-7612-11eb-9111-235c37c9fe46.png">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
v1.1
