### ISSUE TITLE
P03-1 (v1.0) sk.31: žiedų skaičius → stiebo ilgis (skaidrės)

### ISSUE THREAD

**Issue by rstumbraite** [mokymai/taisymai-2021#203]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P02-1 v1.0
4. **Skaidrės numeris:** 31
5. **Glaustai aprašykite netikslumą:** loginė klaida (kopijavimo klaida)
6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Žiedų skaičius
7. **Netikslumo tekstas:** Žiedų skaičius
8. **Siūlomas taisymo tekstas:** Stiebo ilgis (cm)
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="583" alt="image" src="https://user-images.githubusercontent.com/78716050/108896557-c10e4880-761d-11eb-9f8d-eef619105f73.png">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
v1.1
