### ISSUE TITLE
Teorijos svetainė: tinklalapiui -> tinklapiui (rašybos klaida)

### ISSUE THREAD

**Issue by gabijavi** [mokymai/taisymai-2021#208]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** Emokymai sistema
3. **Bylos pavadinimas ar nuoroda (URL):** Emokymai sistema. Savaitė Nr. 4
4. **Glaustai aprašykite netikslumą:**  Rašybos klaida  
5. **Nukopijuokite visą sakinį su netikslumu:** "Paspauskite nuorodą ir užsikrovus tinklalapiui išstudijuokite skyrių „Grafikai kintamųjų porai“  
6. **Netikslumo tekstas:** Tinklalapiui
7. **Siūlomas taisymo tekstas:** Tinklalapiui -> tinklapiui
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![tinklapiui](https://user-images.githubusercontent.com/78655280/109294908-89c6b400-7836-11eb-902a-06f322ef6dcf.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
http://www.vlkk.lt/konsultacijos/3502-web-page-tinklalapis-tinklapis
