### ISSUE TITLE
P04-1(v2.0) sk.30: pasiskirstymas <..> būtų beveik vienodos ->būtų beveik vienodas

### ISSUE THREAD

**Issue by Viktorija30** [mokymai/taisymai-2021#209]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P04-1 (v2.0)
4. **Skaidrės numeris:** ... 30 skaidrė
5. **Glaustai aprašykite netikslumą:** . <..>pogrupyje antrojo požymio pasiskirstymas (proporcijos) būtų beveik vienodos. -> būtų beveik vienodas. Nes sakinio galas bei jo stilistika yra formuluojama, ne pagal šalutines sakinio dalis t.y (proporcijos).
->stilistinė klaida

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**  Jei sąsajos tarp kategorinių kintamųjų nebūtų, kiekviename pirmojo požymio pogrupyje antrojo požymio pasiskirstymas (proporcijos) būtų beveik vienodos
7. **Netikslumo tekstas:** būtų vienodos
8. **Siūlomas taisymo tekstas:** būtų vienodas
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78597896/109295420-651f0c00-7837-11eb-97f0-b8cffae286c1.png)

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [ x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x ] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
v1.1
