### ISSUE TITLE
P04-1(v2.0) sk.37 normalumas tikrinami -> normalumas - tikrinami

### ISSUE THREAD

**Issue by Viktorija30** [mokymai/taisymai-2021#210]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:**P04-1(v2.0) 
4. **Skaidrės numeris:**sk.37
5. **Glaustai aprašykite netikslumą:**  simetrija, išskirčių buvimas, normalumas tikrinami -> praleistas brūkšnelis arba tiesiog žodis yra <- stilistinė klaida

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**  simetrija, išskirčių buvimas, normalumas tikrinami kiekvienam pogrupiui atskirai
7. **Netikslumo tekstas:** normalumas tikrinami
8. **Siūlomas taisymo tekstas:** normalumas - tikrinami ARBA normalumas yra tikrinami
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78597896/109295913-39e8ec80-7838-11eb-83d7-81ad232d4ec1.png)

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Man rodos, tai nėra privalomoji skyryba. Jei klystu, reikia nuorodos į taisyklę LKK puslapyje ar kitur.
