### ISSUE TITLE
P04-2 (v1.0) sk.27: tirinio → turinio (skaidrės)

### ISSUE THREAD

**Issue by domytia** [mokymai/taisymai-2021#211]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P04-2 v1.0 
4. **Skaidrės numeris:** 
5. **Glaustai aprašykite netikslumą:** rašybos klaida

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...grafikų tirinio klaidinančiai atrodo...
7. **Netikslumo tekstas:** tirinio
8. **Siūlomas taisymo tekstas:** turinio
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta. 
![Ekrano kopija (87)](https://user-images.githubusercontent.com/78649673/109304226-9fdb7100-7844-11eb-8e31-43ab2964d91a.png)

...

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
v1.1
