### ISSUE TITLE
Pratybų svetainė: iš → ir (vietoje ir parašyta iš)

### ISSUE THREAD

**Issue by Justas100** [mokymai/taisymai-2021#218]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/bs-2021-pratybos/s04.html
4. **Glaustai aprašykite netikslumą:**  - Vietoje ir parašyta iš
 Rašybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...  rašant programos kodą iš vykdant analizę
6. **Netikslumo tekstas:** Dvi dažniausiai pasitaikančios pradedančiųjų klaidos rašant programos kodą iš vykdant analizę apibendrintos šiose dėžutėse:
7. **Siūlomas taisymo tekstas:** Dvi dažniausiai pasitaikančios pradedančiųjų klaidos rašant programos kodą ir vykdant analizę apibendrintos šiose dėžutėse:
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...
![Klada 7 2](https://user-images.githubusercontent.com/78589786/109477037-39db2d80-7a80-11eb-9660-2d9bd66c1268.png)

Patvirtinkite pažymėdami [x]:

- [ x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
-  [ x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x ] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
![image](https://user-images.githubusercontent.com/12725868/109516373-c56cb280-7ab0-11eb-9609-136a2dac1d22.png)
