### ISSUE TITLE
[emokymai]: venas → vienas (rašybos klaida)

### ISSUE THREAD

**Issue by DomiKontr** [mokymai/taisymai-2021#22]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** emokymuose mokomasis testas nr. 04
3. **Bylos pavadinimas ar nuoroda (URL):** ...
4. **Glaustai aprašykite netikslumą:** antro klausimo 2 sakinyje rašybos klaida
 
5. **Nukopijuokite visą sakinį su netikslumu:**

6. **Netikslumo tekstas:** venas
7. **Siūlomas taisymo tekstas:** vienas
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78689843/107152964-b5f7bf00-6973-11eb-92c8-320b676b56fb.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
1. Apie tokius dalykus (netikslumus teste) reikia rašyti man asmeniškai. Papildomus balus gausite, bet jų skyrimo mechanizmas kitoks.
2. _Print-screen_e reikia pabraukti netikslumo vietą.
3. Taip pat būtina teisingai užpildyti pavadinimą, o ne palikti numatytuosius įrašus. (Aišku, dėl testo tai gerai, kad nepildėte).
4. Testus vadinkite pagal jų kodus. Šiuo atveju M01-4 yra 3 testas.

Dėkui už pranešimą.

**Comment by DomiKontr** [comment]
Sveiki, turėsiu omenyje.


________________________________
