### ISSUE TITLE
Teorijos svetainė: proove → prove (rašybos klaida)

### ISSUE THREAD

**Issue by Milda-Milciute** [mokymai/taisymai-2021#242]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/tyrimu-eiga.html
4. **Glaustai aprašykite netikslumą:**  rašybos klaida

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Kodėl teiginio neįmanoma „moksliškai įrodyti“ (angl. proove), bet galima paneigti, parodyti, kad jis yra klaidingas (angl. falsify)?
6. **Netikslumo tekstas:** proove
7. **Siūlomas taisymo tekstas:** prove
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78533307/110199428-083bdb00-7e61-11eb-94a1-b9ab9504dd08.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
OK, mano žodynas rodė neteisingai: https://en.wiktionary.org/wiki/proove

Dėkui.
