### ISSUE TITLE
Teorijos svetainė: metodai sukurti -> metodai yra sukurti

### ISSUE THREAD

**Issue by Viktorija30** [mokymai/taisymai-2021#243]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/tyrimu-planavimas.html
4. **Glaustai aprašykite netikslumą:**  Trūksta žodžio yra arba brūkšnelio -> Loginė klaida.
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** <.>statistinių išvadų darymo metodai sukurti<.>
6. **Netikslumo tekstas:** metodai sukurti
7. **Siūlomas taisymo tekstas:** metodai -sukurti, arba metodai yra sukurti. Galimas tiesiog ir kablelis po metodai.
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78597896/110204465-c9ffe500-7e7b-11eb-9ed0-d19cef068b6d.png)

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Šioje vietoje nematau, kad būtų klaida.
