### ISSUE TITLE
programa-r: DataCamp kvietimas atrodo kitaip

### ISSUE THREAD

**Issue by DomiKontr** [mokymai/taisymai-2021#25]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/programa-r/paskyros.html
4. **Glaustai aprašykite netikslumą:**  kitaip atrodo pakvietimas į DataCamp grupę.

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ... 
6. **Netikslumo tekstas:** ...
7. **Siūlomas taisymo tekstas:** ...
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78689843/107153930-c6f6ff00-6978-11eb-8df1-62a86d9eae31.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Instrukcijas ėmiau iš oficialaus _DataCamp_ forumo. Kvietimo forma kas kurį laiką keičiasi (praeitą  semestrą buvo mėlyna). Bet esmė ta pati.
 Be to panašu, kad dalis laiško savybių jūsų sistemoje blokuojama:
 
![image](https://user-images.githubusercontent.com/12725868/107154065-8d72c380-6979-11eb-9378-a01160345337.png)

Tai gali daryti naršyklė, el.pašto sistema ar antivirusinė programa.
