### ISSUE TITLE
Teorijos svetainė: nebent: Veikla -> nebent: veikla

### ISSUE THREAD

**Issue by Viktorija30** [mokymai/taisymai-2021#250]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://emokymai.vu.lt/course/view.php?id=6773
4. **Glaustai aprašykite netikslumą:** po dvitaškio nereikia pradėti didžiąja raide. <rašybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Negalima, nebent: Veikla U01 – Įvadas į R yra pažymėta kaip užbaigta.
6. **Netikslumo tekstas:** . nebent: Veikla
7. **Siūlomas taisymo tekstas:** nebent: veikla
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

![image](https://user-images.githubusercontent.com/78597896/110300838-13793d00-8000-11eb-950c-7b983f76fff0.png)

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x ] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Deja, šitie užrašai yra automatiškai sugeneruojami „Emokymai“ sistemos ir nuo manęs nepriklauso.
