### ISSUE TITLE
P02-1 (v2.2) sk.58: kvantilis - yra konkretus → kvantilis - konkretus (skaidrės)

### ISSUE THREAD

**Issue by bilduks** [mokymai/taisymai-2021#255]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P02-1 v2.2
4. **Skaidrės numeris:** ... 
5. **Glaustai aprašykite netikslumą:** skyryba; turi būti "_yra_" arba brūkšnys (negali būti abu)
6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**  "Imties kvantilis – yra konkretus skaičius..." 
7. **Netikslumo tekstas:** " – yra "
8. **Siūlomas taisymo tekstas:** "Imties kvantilis – konkretus skaičius..."
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...
![image](https://user-images.githubusercontent.com/78542953/110354516-ec8f2b00-8040-11eb-91af-4c2e72419d4a.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
@bilduks, kodėl jūsų nurodyta skaidrių versija yra v2.2?
