### ISSUE TITLE
Pratybų svetainė: tikrinant jį rekomenduoju → tikrinant jį, rekomenduoju

### ISSUE THREAD

**Issue by Viktorija30** [mokymai/taisymai-2021#262]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/bs-2021-pratybos/s06.html#uzduotis-u03
4. **Glaustai aprašykite netikslumą:**  trūksta kablelio ->skyrybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** prieš tikrinant jį rekomenduoju įsikelti į 
6. **Netikslumo tekstas:** tikrinant jį rekomenduoju
7. **Siūlomas taisymo tekstas:** tikrinant jį, rekomenduoju
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78597896/110997324-e7eead80-8385-11eb-9bf3-73b97f1c77dc.png)

Patvirtinkite pažymėdami [x]:

- [ x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [ x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x ] Formą užpildžiau tinkamai.

**Comment by rstumbraite** [comment]
Labas! Nėra privaloma kableliu skirti šios išplėstinės aplinkybės :)
[http://www.vlkk.lt/konsultacijos/7453-aplinkybe-isplestine-dalyvine-padalyvine-ar-pusdalyvine](url)
