### ISSUE TITLE
Teorijos svetainė:  sukūriame -> sukuriame (rašybos klaida)

### ISSUE THREAD

**Issue by austejaru** [mokymai/taisymai-2021#266]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/ats-d-skirstiniai.html
4. **Glaustai aprašykite netikslumą:**   Rašybos klaida

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** taisyklė, pagal kurią sukūriame apibūdintą  
6. **Netikslumo tekstas:** sukūriame
7. **Siūlomas taisymo tekstas:** sukuriame (pagal veiksmažodį kurti)
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![Screenshot (885)_LI](https://user-images.githubusercontent.com/78702404/111071410-bb9a7480-84de-11eb-8d1b-e5f3d71cf8cb.jpg)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Pasikartojantis: #258
