### ISSUE TITLE
Teorijos svetainė: Be to → Be to, (skyryba)

### ISSUE THREAD

**Issue by golendraite** [mokymai/taisymai-2021#273]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/tyrimu-planavimas.html
4. **Glaustai aprašykite netikslumą:**  Įterpinys neišskirtas kableliais (skyrybos klaida)

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Be to analogišką rezultatą galime 
6. **Netikslumo tekstas:** Be to
7. **Siūlomas taisymo tekstas:** Be to, 
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
9. 
![image](https://user-images.githubusercontent.com/78824109/111227373-233de600-85eb-11eb-92d0-61383af4c914.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Geriausia su tokiu pranešimu apie skyrybą pateikti ir nuorodą į atitinkamą VLK tinklalapį.
http://www.vlkk.lt/konsultacijos/3170-be-to
