### ISSUE TITLE
Teorijos svetainė: stjudento → studento (teksto suvedimo klaida)

### ISSUE THREAD

**Issue by EvelinaMiz** [mokymai/taisymai-2021#278]
https://mokymai.github.io/biostatistika/skirstiniai-ir-uzdaviniai.html: stjudento → studento (teksto suvedimo klaida)

x

1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/skirstiniai-ir-uzdaviniai.html
4. **Glaustai aprašykite netikslumą:**  
 rašybos klaida
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**  atsitiktinai pasirinkta iš Stjudento t skirstinio  
6. **Netikslumo tekstas:** stjudento
7. **Siūlomas taisymo tekstas:** studento
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...
![image](https://user-images.githubusercontent.com/78542251/111543121-4c8d7c00-877b-11eb-9dc6-ba4eeb2d6056.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Tai statistikos terminas: ne studento, o _Stjudento_, pagal tarimą, gal net _Stjūdento_ reiktų rašyti.
