### ISSUE TITLE
Pratybų svetainė: fregmentų → fragmentų

### ISSUE THREAD

**Issue by Viktorija30** [mokymai/taisymai-2021#279]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/bs-2021-pratybos/s07.html
4. **Glaustai aprašykite netikslumą:**  klaida žodyje

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
![image](https://user-images.githubusercontent.com/12725868/111607072-95c3e700-87e0-11eb-938f-affea7785d65.png)

![image](https://user-images.githubusercontent.com/12725868/111607105-9f4d4f00-87e0-11eb-8304-4de727856daa.png)

Pataisykite!
