### ISSUE TITLE
[T05 testas VMA]: išrenkama → išrenka (rašybos klaida)

### ISSUE THREAD

**Issue by rstumbraite** [mokymai/taisymai-2021#284]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** T05 testas VMA, vienas klausimas
3. **Bylos pavadinimas ar nuoroda (URL):** https://emokymai.vu.lt/mod/quiz/view.php?id=146962
4. **Glaustai aprašykite netikslumą:**  rašybos klaida 
5. **Nukopijuokite visą sakinį su netikslumu:**  Iš visų mieste esančių namų sąrašo kompiuteris visiškai atsitiktinai išrenkama 100 namų.
6. **Netikslumo tekstas:** išrenkama
7. **Siūlomas taisymo tekstas:** išrenka
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
(dėl sąžiningumo nepridėsiu ekrano nuotraukos, nes T05 testas dar nėra uždarytas)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
@rstumbraite, parašykite man apie tai asmenine žinute ir nurodykite klausimo numerį. Nes kol kas nerandu, kad tokia klaida būtų.
