### ISSUE TITLE
Pratybų svetainė: e. e. → e. f. (du kartus pasikartoja punktas e.)

### ISSUE THREAD

**Issue by Enimilia** [mokymai/taisymai-2021#290]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/bs-2021-pratybos/s07.html#s07-pertvarkymas
4. **Glaustai aprašykite netikslumą:**   10.2 užduoties 4. dalyje du kartus pasikartoja punktas e.

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** e. Kiekvieno dokumento pradžioje <...> e.  Žemiau 
6. **Netikslumo tekstas:** e. Kiekvieno dokumento pradžioje <...> e.  Žemiau 
7. **Siūlomas taisymo tekstas:** e. Kiekvieno dokumento pradžioje <...> f.  Žemiau 
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...

![image](https://user-images.githubusercontent.com/78637337/111915406-c88b0b00-8a7e-11eb-9994-23b0eded623f.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
md sintaksės klaida: mažai tarų 3 lygio elementui.
