### ISSUE TITLE
P08-2 (v1.0) sk.16: trūki linija → trūkio linija(skaidrės)

### ISSUE THREAD

**Issue by slavinskaitek** [mokymai/taisymai-2021#294]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P... v...  P08-2 (v1.0)
4. **Skaidrės numeris:** 16
5. **Glaustai aprašykite netikslumą:** Trūksta o raidės
rašybos klaida
6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ... trūki linija
7. **Netikslumo tekstas:** Vientisa linija – 1 laisvės laipsnis, trūki linija - 100 laisvės laipsnių. 
8. **Siūlomas taisymo tekstas:** Vientisa linija – 1 laisvės laipsnis, trūkio linija - 100 laisvės laipsnių.
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![Inked2021-03-28_LI](https://user-images.githubusercontent.com/78700373/112753099-ead0db80-8fde-11eb-85a7-953b13b40275.jpg)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Čia iš tiesų ir turėjo būti "trūki linija".

Beje, žinau, kas yra "trūkio taškas", bet nesu tikras, ar žinau, kas yra "trūkio linija".
