### ISSUE TITLE
P09-1 (v1.0) sk.21: parodanti kuri → parodanti, kuri (skaidrės)

### ISSUE THREAD

**Issue by rstumbraite** [mokymai/taisymai-2021#316]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P09-1 v1.0
4. **Skaidrės numeris:** 21
5. **Glaustai aprašykite netikslumą:** skyrybos klaida (tai privalomoji skyryba)
6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Reikšmingumo lygmuo yra tyrėjo pasirinkta tikimybė, parodanti kuri dalis...
7. **Netikslumo tekstas:** parodanti kuri
8. **Siūlomas taisymo tekstas:** parodanti, kuri
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="826" alt="image" src="https://user-images.githubusercontent.com/78716050/115755665-41df8b80-a3a6-11eb-8987-d2cda3819cfe.png">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Pataisyta v1.1
