### ISSUE TITLE
biostatistika: svetainė: netikslumas grafiko antraštėje->ištrinti žodį ką

### ISSUE THREAD

**Issue by Viktorija30** [mokymai/taisymai-2021#32]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/koreliacija.html
4. **Glaustai aprašykite netikslumą:**   Loginė klaida - ištrinti žodį ką, arba pakeisti sakinio struktūrą.
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** <...> ką Pearson koreliacijos koeficientas parodo tiesinės sąsajos stiprumą<...>  
6. **Netikslumo tekstas:** ką
7. **Siūlomas taisymo tekstas:** ištrinti žodį ką
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

![Screenshot 2021-02-07 21 31 03](https://user-images.githubusercontent.com/78597896/107157573-73db7700-698d-11eb-9f9d-81793c72dc02.png)

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Ši dalis dar nėra parengta, tad taškai neturėtų būti duodami. Bet jūs turbūt dar nematėte pirmosios paskaitos.
