### ISSUE TITLE
P10-2 (v1.0) sk.23: kovariacija padalinta → kovariacija, padalinta (skyrybos klaida)

### ISSUE THREAD

**Issue by rstumbraite** [mokymai/taisymai-2021#334]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P10-2 v1.0
4. **Skaidrės numeris:** 23
5. **Glaustai aprašykite netikslumą:** skyrybos klaida (tai privalomoji skyryba)
6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Tiesinė koreliacija – tai kovariacija padalinta iš standartinių nuokrypių.
7. **Netikslumo tekstas:** kovariacija padalinta
8. **Siūlomas taisymo tekstas:** kovariacija, padalinta
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="847" alt="image" src="https://user-images.githubusercontent.com/78716050/116808600-61af4600-ab42-11eb-8bd3-27be849369dd.png">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
v1.1
