### ISSUE TITLE
S12-2: Fišetio → Fišerio (rašybos klaida)

### ISSUE THREAD

**Issue by austejaru** [mokymai/taisymai-2021#340]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** S12 RStudio projektas
3. **Bylos pavadinimas ar nuoroda (URL):** S12-2--sablonas--rysys-kategoriniai--v1.3.Rmd
4. **Glaustai aprašykite netikslumą:** Rašybos klaida
 
5. **Nukopijuokite visą sakinį su netikslumu:** ...

6. **Netikslumo tekstas:** Fišetio
7. **Siūlomas taisymo tekstas:** Fišerio
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![Screenshot (1249)_LI](https://user-images.githubusercontent.com/78702404/117546488-545af580-b033-11eb-8e7d-a5c5e6dc1091.jpg)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Kartojasi: #335
