### ISSUE TITLE
Teorijos svetainė: 3. Tyrimų planavimas. Neveikianti nuoroda

### ISSUE THREAD

**Issue by dstepanovas** [mokymai/taisymai-2021#388]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/tyrimu-planavimas.html#tikrumas-glaudumas
4. **Glaustai aprašykite netikslumą:**  neveikia nuoroda/nerodo paveikslėlio

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** Pav. 3.1: Tikslumas: tikrumas ir glaudumas atvaizduoti kaip šūviai į taikinį. Šaltinis: 
6. **Netikslumo tekstas:** Pav. 3.1: Tikslumas: tikrumas ir glaudumas atvaizduoti kaip šūviai į taikinį. Šaltinis:
7. **Siūlomas taisymo tekstas:** -
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/78704599/120555304-8e85a000-c403-11eb-9fee-1e935aec4f6d.png)

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [ x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x ] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Problemos nematau:
![image](https://user-images.githubusercontent.com/12725868/120710707-24ceca00-c4c7-11eb-992b-c1018a2752ea.png)
Gal laikini interneto ryšio sutrikimai?
