### ISSUE TITLE
[*]: Papildomi balai už pirmą pranešimą

### ISSUE THREAD

**Issue by Setaria-pumila** [mokymai/taisymai-2021#6]
1. **Dalykas:** BS-2021      
2. **Data:** 2021-9-3      
3. **Tema:** Papildomi balai už pirmą pranešimą

**Comment by GegznaV** [comment]
@Setaria-pumila, datas geriausia rašyti paliekant priekyje esančius nulius, pvz., 2021-09-03. Jei datą reiktų nuskaityti kompiuteriu, tokį formatą būtų nuskaityti lengviau.
