### ISSUE TITLE
[emokymai]: M01-3 neatitinka skaidrių→ pataisyti testą

### ISSUE THREAD

**Issue by MartynasArba** [mokymai/taisymai-2021#83]
1. **Kursas:** Biostatistika (BS-2021)
2. emokymai.vu.lt Savaitė nr. 1, M01-3 testas
3. **Bylos pavadinimas ar nuoroda (URL):** https://emokymai.vu.lt/mod/quiz/view.php?id=146933
4. **Glaustai aprašykite netikslumą:**  teste atsakius, kad užtenka egzaminą išlaikyti 40%, žymima kaip klaida, nors skaidrėse sakoma priešingai.
5. **Nukopijuokite visą sakinį su netikslumu:** Kiek minimaliai balų už teorinės dalies egzaminą reikia surinkti, kad jis būtų išlaikytas? 
(Atsakymas yra skaičius nuo 0 iki 10 dviejų skaičių po kablelio tikslumu. Sistema neatpažįsta kablelių, todėl atsakymą reikia rašyti su tašku, pvz., „9.9“, o ne „9,9“)
 Išlaikyta, jei surenkama 40% ar daugiau;

6. **Netikslumo tekstas:** ...
7. **Siūlomas taisymo tekstas:** ...
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta. Prikabinta apačioje.

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos vietą ir esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Klausia, kiek balu, o ne procentų. Tad kiek balų sudaro 40% egzamino pažymio?

**Comment by GegznaV** [comment]
![image](https://user-images.githubusercontent.com/12725868/107257167-11dd4900-6a43-11eb-9037-bfd58c3dc8db.png)
