### ISSUE TITLE
programa-r: prisijunti→ prisijungti (rašyba)

### ISSUE THREAD

**Issue by Kamilekasp** [mokymai/taisymai-2021#89]
1. **Kursas:** Biostatistika (BS-2021)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/programa-r/paskyros.html#vu-email
4. **Glaustai aprašykite netikslumą:**  Gramatinė klaida (vietoj prisijunti --> prisijungti).
5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ...iš sistemos „DataCamp“ – pakvietimas prisijunti, todėl dėžutę tikrinkite...
6. **Netikslumo tekstas:** prisijunti
7. **Siūlomas taisymo tekstas:** prisijungti
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="598" alt="1" src="https://user-images.githubusercontent.com/78532385/107234621-8953ae00-6a2c-11eb-82f2-a98b4bd4d8fb.png">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Pavadinime turi matytis konkretus netikslumas ir konkretus taisymas, o ne `netikslumas → taisymas (netikslumo esmė)`

**Comment by GegznaV** [comment]
Visai taip pat, kaip rašėte `Glaustai aprašykite netikslumą: Gramatinė klaida (vietoj prisijunti --> prisijungti).`
